
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springboot
    password: springboot
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCTSERVICE 
server:
  port: 8090
   
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka  # Fix: Change 'defaultzone' to 'defaultZone'
#  instance:
#    prefer-ip-address: true
